import { useEffect,useMemo,useState } from 'react';
import { backendApi } from '@/adapters/backendApi';
type Row={id:number;title:string;priority:string;status:string;created_at:string;closed_at?:string;required_date?:string;client:string;branch:string;technician:string;resolution_hours:number};
const status:Record<string,string>={open:'Abierto',assigned:'Asignado',in_progress:'En proceso',finished:'Finalizado',closed:'Cerrado'};
export default function AdminReportsPage(){
 const [period,setPeriod]=useState('month'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[rows,setRows]=useState<Row[]>([]),[summary,setSummary]=useState<Record<string,number>>({}),[note,setNote]=useState(localStorage.getItem('report-note')||'');
 const load=()=>backendApi.get('/reports/detail',{params:{period,from:period==='custom'?from:undefined,to:period==='custom'?to:undefined}}).then(r=>{setRows(r.data.data.rows);setSummary(r.data.data.summary)});
 useEffect(()=>{load()},[period]);
 const csv=()=>{const head=['ID','Fecha','Cliente','Sucursal','Ticket','Prioridad','Estado','Tecnico','Horas'];const body=rows.map(r=>[r.id,new Date(r.created_at).toLocaleString('es-GT'),r.client,r.branch,r.title,r.priority,status[r.status]||r.status,r.technician,r.resolution_hours]);const content=[head,...body].map(x=>x.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+content],{type:'text/csv'}));a.download=`reporte-tickets-${new Date().toISOString().slice(0,10)}.csv`;a.click()};
 const cards=useMemo(()=>[['Total',summary.total||0],['Abiertos',summary.open||0],['Asignados',summary.assigned||0],['En proceso',summary.in_progress||0],['Finalizados',(summary.finished||0)+(summary.closed||0)]], [summary]);
 return <div className="p-4 md:p-6 space-y-5"><div><p className="text-sm text-default-500">Administración</p><h1 className="text-2xl font-semibold">Reportes e historial</h1><p className="text-sm text-default-500">Consulta semanal, mensual o por fechas y exporta el detalle.</p></div>
 <div className="card p-4 flex flex-wrap gap-3 items-end"><label className="text-sm">Periodo<select className="form-select mt-1 block" value={period} onChange={e=>setPeriod(e.target.value)}><option value="week">Semana actual</option><option value="month">Mes actual</option><option value="custom">Rango de fechas</option></select></label>{period==='custom'&&<><label className="text-sm">Desde<input className="form-input mt-1 block" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">Hasta<input className="form-input mt-1 block" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn bg-primary text-white" onClick={load}>Aplicar</button></>}<button className="btn border border-default-200" onClick={csv}>Descargar CSV</button></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([a,b])=><div className="card p-4" key={String(a)}><p className="text-sm text-default-500">{a}</p><p className="text-2xl font-semibold">{b}</p></div>)}</div>
 <div className="card p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold">Historial detallado</h2><p className="text-sm text-default-500">Fechas, cliente, técnico, prioridad, estado y tiempo de atención.</p></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-default-200 text-left">{['ID','Fecha','Cliente','Sucursal','Ticket','Prioridad','Estado','Técnico','Horas'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-b border-default-100" key={r.id}><td className="p-3">#{r.id}</td><td className="p-3 whitespace-nowrap">{new Date(r.created_at).toLocaleDateString('es-GT')}</td><td className="p-3">{r.client}</td><td className="p-3">{r.branch}</td><td className="p-3">{r.title}</td><td className="p-3">{r.priority}</td><td className="p-3">{status[r.status]||r.status}</td><td className="p-3">{r.technician}</td><td className="p-3">{r.resolution_hours}</td></tr>)}{!rows.length&&<tr><td className="p-6 text-center text-default-500" colSpan={9}>No hay tickets en el periodo seleccionado.</td></tr>}</tbody></table></div></div>
 <div className="card p-4"><h2 className="font-semibold">Observaciones editables del reporte</h2><textarea className="form-textarea mt-3 w-full" rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Agrega conclusiones, incidencias o notas del periodo..."/><button className="btn bg-primary text-white mt-3" onClick={()=>localStorage.setItem('report-note',note)}>Guardar observaciones</button></div></div>
}
