import { useEffect,useState } from 'react';
import { backendApi } from '@/adapters/backendApi';
import { userStorage } from '@/services/authService';
import { LuTicket,LuClock3,LuCircleCheckBig,LuWrench,LuCirclePlus,LuBell } from 'react-icons/lu';
import { Link } from 'react-router-dom';
type Summary={total?:number;open?:number;assigned?:number;in_progress?:number;completed?:number;scheduled?:number};
export default function RoleDashboard({role}:{role:'client'|'technician'}){
 const user=userStorage.get(); const [data,setData]=useState<Summary>({}); const [error,setError]=useState('');
 useEffect(()=>{backendApi.get(`/dashboard/${role}`).then(r=>setData(r.data.data)).catch(()=>setError('No fue posible cargar los indicadores.'));},[role]);
 const cards=role==='client'?[['Mis tickets',data.total,LuTicket],['Abiertos',data.open,LuClock3],['En proceso',data.in_progress,LuWrench],['Finalizados',data.completed,LuCircleCheckBig]]:[['Asignados',data.assigned,LuTicket],['En proceso',data.in_progress,LuWrench],['Finalizados',data.completed,LuCircleCheckBig],['Servicios programados',data.scheduled,LuClock3]];
 return <main className="p-5"><div className="mb-6"><p className="text-sm text-default-500">Cerrajería Ramírez, S.A.</p><h1 className="text-2xl font-semibold">{role==='client'?'Portal del cliente':'Panel técnico'}</h1><p className="text-default-500">Bienvenido, {user?.firstName}. {role==='client'?'Consulta y da seguimiento a tus solicitudes.':'Revisa los servicios que tienes asignados y actualiza su avance.'}</p></div>{error&&<div className="mb-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon]:any)=><div className="card p-5" key={label}><div className="flex items-center justify-between"><div><p className="text-sm text-default-500">{label}</p><p className="mt-2 text-3xl font-semibold">{value??0}</p></div><Icon className="text-3xl text-primary"/></div></div>)}</div><div className="mt-6 grid gap-4 md:grid-cols-2">{role==='client'?<><Link to="/tickets" className="card p-6 hover:border-primary"><LuCirclePlus className="mb-3 text-3xl text-primary"/><h2 className="font-semibold">Crear nueva solicitud</h2><p className="text-sm text-default-500">Registra una incidencia o un proyecto nuevo con prioridad, descripción, ubicación y fecha requerida.</p></Link><Link to="/notifications" className="card p-6 hover:border-primary"><LuBell className="mb-3 text-3xl text-primary"/><h2 className="font-semibold">Notificaciones</h2><p className="text-sm text-default-500">Consulta las actualizaciones relacionadas con tus tickets.</p></Link></>:<><Link to="/tickets" className="card p-6 hover:border-primary"><LuTicket className="mb-3 text-3xl text-primary"/><h2 className="font-semibold">Tickets asignados</h2><p className="text-sm text-default-500">Actualiza el estado del servicio y registra el trabajo realizado.</p></Link><Link to="/services-calendar" className="card p-6 hover:border-primary"><LuClock3 className="mb-3 text-3xl text-primary"/><h2 className="font-semibold">Agenda de servicios</h2><p className="text-sm text-default-500">Consulta los servicios programados para tu usuario técnico.</p></Link></>}</div></main>
}
