import { useEffect, useState } from 'react';
import { backendApi } from '@/adapters/backendApi';

type Row = Record<string, unknown> & { id?: string | number };
const labels: Record<string, string> = { users: 'Usuarios y roles', notifications: 'Notificaciones', files: 'Archivos y evidencias', 'reports/technicians': 'Productividad de técnicos', 'service-history': 'Historial de servicios', surveys: 'Encuestas de satisfacción' };

export default function SecondaryListPage({ resource }: { resource: keyof typeof labels }) {
  const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { let active = true; setLoading(true); backendApi.get<{ data: Row[] }>(`/${resource}`, { params: { page: 1, limit: 100 } }).then(({ data }) => { if (active) setRows(data.data ?? []); }).catch(() => { if (active) setError('No se pudo cargar la información.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [resource]);
  if (resource === 'notifications') return <div className="p-4 md:p-6"><div className="mb-6"><p className="mb-1 text-sm text-default-500">Comunicación</p><h1 className="text-2xl font-semibold text-default-900">Notificaciones</h1><p className="mt-1 text-sm text-default-500">Consulta de forma clara los cambios de tus tickets y servicios.</p></div>{error&&<div className="mb-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}<div className="space-y-3">{loading?<div className="card p-10 text-center">Cargando...</div>:rows.length===0?<div className="card p-10 text-center text-default-500">No hay notificaciones recientes.</div>:rows.map(row=><div key={String(row.id)} className="card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">{row.ticket_id?`Ticket #${String(row.ticket_id)}`:'Sistema'}</span><span className="text-xs text-default-400">{row.status==='sent'?'Enviada':row.status==='failed'?'No enviada':'Pendiente'}</span></div><h2 className="mt-3 font-semibold text-default-900">{String(row.subject||'Actualización del sistema')}</h2><p className="mt-1 text-sm text-default-600">{String(row.message||'Sin detalle')}</p></div><time className="text-xs text-default-400">{row.created_at?new Date(String(row.created_at)).toLocaleString('es-GT',{dateStyle:'medium',timeStyle:'short'}):''}</time></div></div>)}</div></div>;
  return <div className="p-4 md:p-6"><div className="mb-6"><p className="mb-1 text-sm text-default-500">Operación</p><h1 className="text-2xl font-semibold text-default-900">{labels[resource]}</h1></div>{error && <div className="mb-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</div>}<div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-default-50"><tr><th className="p-4">ID</th><th className="p-4">Información</th></tr></thead><tbody>{loading ? <tr><td colSpan={2} className="p-10 text-center">Cargando...</td></tr> : rows.length === 0 ? <tr><td colSpan={2} className="p-10 text-center">No hay registros.</td></tr> : rows.map(row => <tr key={String(row.id)} className="border-t border-default-100"><td className="p-4 font-mono">{String(row.id ?? '—')}</td><td className="max-w-4xl whitespace-pre-wrap p-4">{Object.entries(row).filter(([key]) => key !== 'id').map(([key, value]) => `${key}: ${String(value ?? '—')}`).join(' · ')}</td></tr>)}</tbody></table></div></div></div>;
}
