import type { IconType } from 'react-icons/lib';
import { LuBell, LuCalendarDays, LuChartNoAxesCombined, LuClipboardCheck, LuFileImage, LuFolderKanban, LuLayoutDashboard, LuTicket, LuUserCog, LuUsers, LuBuilding2, LuCirclePlus } from 'react-icons/lu';
export type MenuItemType={key:string;label:string;isTitle?:boolean;href?:string;children?:MenuItemType[];icon?:IconType;parentKey?:string;target?:string;isDisabled?:boolean};
const admin:MenuItemType[]=[
 {key:'system',label:'Sistema de soporte',isTitle:true},{key:'dashboard',label:'Panel principal',icon:LuLayoutDashboard,href:'/dashboard'},{key:'tickets',label:'Tickets e incidencias',icon:LuTicket,href:'/tickets'},{key:'services',label:'Calendario de servicios',icon:LuCalendarDays,href:'/services-calendar'},{key:'clients',label:'Clientes y sucursales',icon:LuUsers,href:'/clients'},{key:'projects',label:'Proyectos',icon:LuFolderKanban,href:'/projects'},
 {key:'operations',label:'Operación',isTitle:true},{key:'technicians',label:'Técnicos y asignaciones',icon:LuUserCog,href:'/ticket-control'},{key:'history',label:'Historial de servicios',icon:LuClipboardCheck,href:'/service-history'},{key:'files',label:'Archivos y evidencias',icon:LuFileImage,href:'/files'},{key:'surveys',label:'Encuestas de satisfacción',icon:LuClipboardCheck,href:'/surveys'},{key:'notifications',label:'Notificaciones',icon:LuBell,href:'/notifications'},{key:'reports',label:'Reportes',icon:LuChartNoAxesCombined,href:'/reports'},
 {key:'administration',label:'Administración',isTitle:true},{key:'users',label:'Usuarios y roles',icon:LuUserCog,href:'/users'},{key:'branches',label:'Sucursales',icon:LuBuilding2,href:'/branches'}];
const client:MenuItemType[]=[{key:'client-title',label:'Portal del cliente',isTitle:true},{key:'client-dashboard',label:'Mi panel',icon:LuLayoutDashboard,href:'/client-dashboard'},{key:'new-ticket',label:'Crear ticket',icon:LuCirclePlus,href:'/tickets'},{key:'my-tickets',label:'Mis tickets',icon:LuTicket,href:'/tickets'},{key:'client-calendar',label:'Calendario de servicios',icon:LuCalendarDays,href:'/services-calendar'},{key:'client-history',label:'Historial de servicios',icon:LuClipboardCheck,href:'/service-history'},{key:'client-survey',label:'Encuesta de satisfacción',icon:LuClipboardCheck,href:'/surveys'},{key:'client-notifications',label:'Notificaciones',icon:LuBell,href:'/notifications'}];
const technician:MenuItemType[]=[{key:'tech-title',label:'Panel técnico',isTitle:true},{key:'tech-dashboard',label:'Mi panel',icon:LuLayoutDashboard,href:'/technician-dashboard'},{key:'tech-tickets',label:'Tickets asignados',icon:LuTicket,href:'/tickets'},{key:'tech-calendar',label:'Calendario de servicios',icon:LuCalendarDays,href:'/services-calendar'},{key:'tech-history',label:'Historial de servicios',icon:LuClipboardCheck,href:'/service-history'},{key:'tech-files',label:'Archivos y evidencias',icon:LuFileImage,href:'/files'}];
export function menuForRole(role?:string){return role==='client'?client:role==='technician'?technician:admin;}
export const menuItemsData=admin;
